library(ape)
set.seed(2)
tree <- rcoal(100)
tree$edge.length <- tree$edge.length/max(branching.times(tree))
par(mfcol=c(3,1))
plot(tree, show.tip.label = F)
set.seed(7)
body.size <- rTraitCont(phy = tree, model = "BM", root.value = 100)
brain.size <- rTraitCont(phy = tree, model = "BM", root.value = 10)
plot(brain.size~body.size)
fit <- lm(brain.size~body.size)
summary(fit)
plot(brain.size~body.size, col=c(rep("blue",68),rep("red",32)),pch=16)
fit2 <- lm(brain.size[69:100]~body.size[69:100])
summary(fit2)
