---
title: "Comparison of TSSSE model and BiSSE"
author: "Heath Blackmon"
date: "December 12, 2015"
output: html_document
---

# Introduction and Data

Part of the NSF grant is our idea for a semi-non-Markovian model of discrete trait evolution we will call this the temporary state approach (TSSSE).  We are thinking that we might be able to sell this as a biologically more realistic model that might mitigate some of the high false positive rate that we are currently producing using BiSSE.  The goal here then is just to simulate some data under this model and analyze under TSSSE and BiSSE.  What happens when we have the wrong model?  Also compare data where we have a real tree and we evolve some binary trait then analyze with both does BiSSE or TSSSE perform much better/worse? (if we want to think about a trait like this perhaps ploidy or selfcompatability make sense)

lets simulate data under TSSSE
```{r}
library(diversitree)
musse.data <- vector(mode="list", length=100)
pars <- c(0.10, 0.20, 0.10, # lambda 1, 2, 3
          0.01, 0.01, 0.01, # mu 1, 2, 3
          0.01, 0.00,       #q12, q13
          0.00, 0.05,       #q21, q23
          0.00, 0.00)       #q31, q32

for(i in 1:100){
  set.seed(i)
  musse.data[[i]] <- tree.musse(pars, max.taxa=200, x0=1)
}
```


