---
title: "Permutation and correlation example"
author: "Heath Blackmon"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Permutation Tests


```{r}
# First lets simulate some data
females <- sample(9:15, size = 25, replace = T)
males <-  sample(7:13, size = 25, replace = T)

# now we can arrange this data into a dataframe
dat <- data.frame(c(females, males),
                  rep(c("female","male"), each=25))
colnames(dat) <- c("size","sex")

# here we calculate our chosen emprical statistics
# in this case we chose the difference in the means of
# our groups
emp.obs <- mean(dat$size[dat$sex=="female"]) - 
  mean(dat$size[dat$sex=="male"])

# this will hold the null distribution that we are about
# simulate
null.dist <- c()

# each time through this loop we will calculate our
# statistic under the assumptions of the null distribution
# (mainly that the sexes have the same size and are random
# draws from the same statistical population)
for(i in 1:10000){
  # this randomizes the sex assignment
  dat$sex <- sample(dat$sex)
  # this calculates one measure of our stat these
  # will all be recorded to form the null distribution
  null.dist[i] <- mean(dat$size[dat$sex=="female"]) - 
    mean(dat$size[dat$sex=="male"])
}
# here we calculate a pvalue
sum(emp.obs <= null.dist)/length(null.dist)

# here we visualize our result
plot(density(null.dist))
abline(v=emp.obs, col="red", lwd=2)
```



## Correlation Tests

For the correlation test we will use the `iris` dataset that is included with R. We will do both a parametric and non parametric version.

```{r}
# first we load the data
data(iris)

# the typical parametric version of the correlation test
cor.test(x=iris$Sepal.Length, y=iris$Petal.Length)

# the non-parametric version
cor.test(x=iris$Sepal.Length, y=iris$Petal.Length,
         method = "spearman")

```



