---
title: "R Intro for beginners"
author: "Heath Blackmon"
output: 
  html_document:
    theme: cosmo
    highlight: kate
---

The pages below were created in preparation for my first course as software carpentry instructor.  I ended up teaching control structures, best practices, plotting, and R markdown.  The control structures were a last minute addition when we ran overtime on our first day.  In the future, I would love to teach this again but with fewer topics.  In particular, I feel like most of the students at this would have enjoyed 2 hours just focused on plotting in R.  Feel free to use or adapt anything that is here.  I have included links to both the html pages and the R markdown pages that created the html pages.  If you have any questions please don't hesitate to email me: <coleoguy@gmail.com>

**Control structures**

This was a quick lesson focusing on using for loops to perform operations on rows of a matrix. Still need to be expanded to include plotting in a loop.

[Control structures in R-document](http://coleoguy.github.io/SWC/lesson-4.html)

[Control structures in Rmd](http://coleoguy.github.io/SWC/lesson-4.Rmd)

[Control structures in R-slides](http://coleoguy.github.io/SWC/lesson-4-slides.html)

[Control structures in Rmd](http://coleoguy.github.io/SWC/lesson-4-slides.Rmd)

**Best practices in R - google version**

This lesson covered the basics of the Software Carpentry best practices lesson and also reviewed much of the style advice in Google's style sheet.

[Best practices in R-document](http://coleoguy.github.io/SWC/lesson-5.html)

[Best practices in R Rmd](http://coleoguy.github.io/SWC/lesson-5.Rmd)

[Best practices in R-slides](http://coleoguy.github.io/SWC/lesson-5-slides.html)

[Best practices in R Rmd](http://coleoguy.github.io/SWC/lesson-5-slides.Rmd)

**Plotting in R - base version**

Using a dataset on the impact of laptops in the classroom as well as the Yellowstone dataset students explore a variety of plots possible with the base plotting package.

[Graphing in R-document](http://coleoguy.github.io/SWC/lesson-6.html)

[Graphing in R-Rmd](http://coleoguy.github.io/SWC/lesson-6.Rmd)

[Graphing in R-slides](http://coleoguy.github.io/SWC/lesson-6-slides.html)

[Graphing in R Rmd](http://coleoguy.github.io/SWC/lesson-6-slides.Rmd)

**Markdown - slides and docs**

Using the chickwts dataset students make slides and html files from their R markdown code.  We explore a variety of chunk options and the basic way that R markdown documents are assembled.

[Sharing research-document](http://coleoguy.github.io/SWC/lesson-7.html)

[Sharing research Rmd](http://coleoguy.github.io/SWC/lesson-7.Rmd)

[Sharing research-slides](http://coleoguy.github.io/SWC/lesson-7-slides.html)

[Sharing research Rmd](http://coleoguy.github.io/SWC/lesson-7-slides.Rmd)


&nbsp;

If you were a student at this workshop.. **THANKS FOR YOUR AWESOME WORK**
