---
title: "homework 1"
author: "Heath Blackmon"
date: '2022-09-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
```

For questions 1,2, and 4 use 1000 simulations to get your answer.

1) You are studying an organisms behavior however the sex can only be determined by dissection after the experiment. You only have enough time and money to observe 10 individuals. What proportion of the time will you have at least three males and three females in your study. Assume that males and females are equally common. Average across 1000 simulations.

2) Now reevaluate if males make up 75% of the population and females make up 25% of the population. Average across 1000 simulations.

3) Probability of flipping heads on a coin 4 times in a row (assume the coin is fair)?

4) We have 99 students in our class. What is the average number of students that will flip 4 heads in a row. Average across 1000 simulations.

5) You create a vector by typing: `x <- c(234, 874, 239, 598)` into R. Demonstrate 3 ways that you can extract 874 and 598 from the matrix:

6) You create a matrix by typing `x <- matrix(1:20, 10, 2)` into R.
Demonstrate three ways in which you could extract the values 17, 18, 19 from the matrix.




