---
title: "Study of comparative methods -- Functions for comparative tests:"
author: "Heath Blackmon"
date: "September 19, 2015"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 2
---

[Return to main website](http://coleoguy.github.io/resources.html)

Return to of comparative methods [outline](http://coleoguy.github.io/comparative/methods.html) page 

Ok, on this page we will just create functions for each of the tests that we want to use and compare.

```{r, echo=F}
load("~/Desktop/pagel.data.sets.RData")
num <- 3
phy <- set.phy[[num]]
dd1 <- dependant.data1[[num]]
dd2 <- dependant.data2[[num]]
id1 <- independant.data1[[num]]
id2 <- independant.data2[[num]]
rb1 <- perfrep1[[num]]
rb2 <- perfrep2[[num]]
ds1 <- state.darwin1[[num]]
ds2 <- state.darwin2[[num]]
ub1 <- unrepburst1[[num]]
ub2 <- unrepburst2[[num]]
rm(dependant.data1, dependant.data2, independant.data1, independant.data2,
   perfrep1, perfrep2, set.phy, state.darwin1, state.darwin2, transitioned1,
   transitioned2, unrepburst1, unrepburst2)
```
___
#Pagel's [1]
```{r}
mark <- function(phy, x, y, strict=F, pars=0.01, method="nlminb"){
  # method options are: optim, subplex, nlminb
  # nlminb is rather robust to starting parameter but
  # but is prone to convergence failure more often than
  # some of the other methods
  z <- paste(x, y, sep="")
  z[z=="00"] <- 1
  z[z=="01"] <- 2
  z[z=="10"] <- 3
  z[z=="11"] <- 4
  z <- as.numeric(z)
  names(z) <- phy$tip.label
  lk1 <- diversitree::make.mkn(phy, z, k=4, strict=F)
  lk1 <- diversitree::constrain(lk1, q14 ~ 0, q23 ~ 0, q32 ~ 0, q41 ~ 0)
  lk2 <- diversitree::constrain(lk1, q13~q24, q31~q42, q21~q43, q12~q34)
  fit1 <- diversitree::find.mle(lk1, rep(pars, 8), method=method)
  fit2 <- diversitree::find.mle(lk2, rep(pars, 4), method=method)
  m.comp <- anova(fit1, fit2)[2,5]
  return(m.comp)
}
```

```{r}
mark(phy, x=dd1, y=dd2)
mark(phy, x=ds1, y=ds2)
mark(phy, x=id1, y=id2)
mark(phy, x=rb1, y=rb2)
mark(phy, x=ub1, y=ub2)
```

___
#citations
[1] Pagel, Mark. "Detecting correlated evolution on phylogenies: a general method for the comparative analysis of discrete characters." Proceedings of the Royal Society of London B: Biological Sciences 255, no. 1342 (1994): 37-45.

[2] Huelsenbeck, John P., Rasmus Nielsen, and Jonathan P. Bollback. "Stochastic mapping of morphological characters." Systematic Biology 52, no. 2 (2003): 131-158.

[3] Maddison, Wayne P. "A method for testing the correlated evolution of two binary characters: are gains or losses concentrated on certain branches of a phylogenetic tree?." Evolution (1990): 539-557.


